title: Jianing "Jed" Yang
logo: /assets/img/logo.jpg
description: B.S. Computer Science @ Georgia Tech
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

cv: /assets/resume_20180619.pdf
linkedin_url: https://www.linkedin.com/in/jedyang/
github_url: https://github.com/jedyang97/